### ISSUE TITLE
Multi-grid Detection?

### ISSUE THREAD

**Issue by csun** [powei-lin/aprilgrid-rs#7]
Hi there, I work at Tangram Vision (with Devon Morris) and we've been testing out this library. I've noticed that, in images with multiple aprilgrids, it will only ever detect one of them at a time. Which one it detects is random, but it will detect all markers from that grid and none of the other. For reference, here's the test image I'm using.

![two_aprilgrid](https://github.com/user-attachments/assets/6d23d659-399c-43a6-9599-93326cc6b19b)

Is there any planned support for multi-grid detection in the future? Alternatively, do you have any suggestions for how to approach this problem if we were to try to upstream a fix?

Thanks for all of your work on this.

**Comment by powei-lin** [comment]
Hi
I've added a [parameter](https://github.com/powei-lin/aprilgrid-rs/blob/621c7e17e74095815fd6f828eb2c9f81032a3e4e/src/detector.rs#L28) for detecting multi boards.

Also in the [unit test](https://github.com/powei-lin/aprilgrid-rs/blob/621c7e17e74095815fd6f828eb2c9f81032a3e4e/tests/test_detector.rs#L32).

**Comment by powei-lin** [comment]
Please update to the latest version (v0.4.0)

**Comment by csun** [comment]
Thanks so much, Powei. It appears to be working now
